# -*- coding: utf-8 -*-
"""EX8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12lnscfE4Jt2ltIxspuFgGNcAlS_vQ-XD
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.cluster import AgglomerativeClustering
from scipy.cluster.hierarchy import dendrogram, linkage

# Generate synthetic data
X, _ = make_blobs(n_samples=30, centers=3, random_state=42, cluster_std=1.0)

# Step 1: Compute the distance matrix and linkage
linkage_matrix = linkage(X, method='ward')

# Step 2: Plot the dendrogram
plt.figure(figsize=(12, 8))
dendrogram(linkage_matrix,  leaf_rotation=90, leaf_font_size=12)
plt.title("Dendrogram for Hierarchical Clustering")
plt.xlabel("Sample Index")
plt.ylabel("Distance")
plt.show()

# Step 3: Apply Agglomerative Clustering
n_clusters = 3  # Number of clusters to form
agglomerative = AgglomerativeClustering(n_clusters=n_clusters, linkage='ward')
y_agg = agglomerative.fit_predict(X)

# Visualize the clustering results
plt.figure(figsize=(10, 6))
plt.scatter(X[:, 0], X[:, 1], c=y_agg, cmap='viridis', marker='o', s=100)
plt.title("Agglomerative Clustering Results")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.show()



