# -*- coding: utf-8 -*-
"""EX7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HnraHc9r3z78_CNFI-uRVK6tCIWfDJbE
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans

# Step 1: Generate synthetic dataset
X, _ = make_blobs(n_samples=300, centers=4, cluster_std=0.6, random_state=42)

# Step 2: Initialize KMeans model
k = 4  # Number of clusters
kmeans = KMeans(n_clusters=k, init='random', n_init=10, max_iter=300, random_state=42)



# Step 3: Fit the model and predict clusters
y_kmeans = kmeans.fit_predict(X)

# Step 4: Plot the data and cluster centroids
plt.figure(figsize=(8, 6))
plt.scatter(X[:, 0], X[:, 1], c=y_kmeans, cmap='viridis', s=50, alpha=0.6, edgecolor='k')
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], s=200, c='red', label='Centroids', marker='X')
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.title('K-means Clustering')
plt.legend()
plt.show()